// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-evzmPuCjeaiLHGHASY4Q6QeI7scx0A',
    appId: '1:11458361673:web:083532c13da4887d798298',
    messagingSenderId: '11458361673',
    projectId: 'equina-5689b',
    authDomain: 'equina-5689b.firebaseapp.com',
    storageBucket: 'equina-5689b.firebasestorage.app',
    measurementId: 'G-0M0MPNJSRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvJkY2EqmafbIm6JxCGE6y3Gb9dt0GCY',
    appId: '1:11458361673:android:7246f91cac7f721d798298',
    messagingSenderId: '11458361673',
    projectId: 'equina-5689b',
    storageBucket: 'equina-5689b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANTKZ1oKv6ZcDM8z2DFpoRaqHrVwSjpd8',
    appId: '1:11458361673:ios:b55bc97a80ce64f3798298',
    messagingSenderId: '11458361673',
    projectId: 'equina-5689b',
    storageBucket: 'equina-5689b.firebasestorage.app',
    iosBundleId: 'com.example.equinaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANTKZ1oKv6ZcDM8z2DFpoRaqHrVwSjpd8',
    appId: '1:11458361673:ios:b55bc97a80ce64f3798298',
    messagingSenderId: '11458361673',
    projectId: 'equina-5689b',
    storageBucket: 'equina-5689b.firebasestorage.app',
    iosBundleId: 'com.example.equinaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh-evzmPuCjeaiLHGHASY4Q6QeI7scx0A',
    appId: '1:11458361673:web:5c549662d9e87eda798298',
    messagingSenderId: '11458361673',
    projectId: 'equina-5689b',
    authDomain: 'equina-5689b.firebaseapp.com',
    storageBucket: 'equina-5689b.firebasestorage.app',
    measurementId: 'G-1YQGVB374M',
  );
}
